name: Build Android APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # 1. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # 2. Instalar DependÃªncias do Sistema (Linux)
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential libtool libtool-bin autoconf automake pkg-config \
            git python3-dev ffmpeg libsdl2-dev libsdl2-image-dev \
            libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev \
            libavformat-dev libavcodec-dev zlib1g-dev libncurses6 libncurses-dev libstdc++6 \
            openjdk-17-jdk unzip zip

      # 3. Instalar Buildozer e Cython
      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      # 4. Compilar (SEM O YES |)
      - name: Build with Buildozer
        run: |
          buildozer android debug

      # 5. Salvar o APK para download
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: escape-hero-apk
          path: bin/*.apk
